In [1]:
import numpy as np
import pandas as pd

In [3]:
from PIL import Image

In [22]:
image = Image.open(r"..\Visualization\38436.png")

In [23]:
image = image.convert('L')

In [24]:
# image = image.convert('L')
image_array = np.array(image)
image_array.shape

(600, 900)

In [25]:
classes = np.unique(image_array, axis=None)
classes

array([ 66, 104, 143, 181, 219], dtype=uint8)

In [26]:
numbers = np.linspace(0, 255, len(classes))

In [27]:
numbers

array([  0.  ,  63.75, 127.5 , 191.25, 255.  ])

In [28]:
for idx,clas in enumerate(classes):
    image_array[image_array==clas] = numbers[idx]

In [29]:
import matplotlib.pyplot as plt

image_rgb = np.repeat(image_array[:, :, np.newaxis], 3, axis=2)

In [31]:
image_rgb

array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [34]:
from PIL import Image

In [37]:
img = Image.fromarray(image_rgb)

In [43]:
img.save(r'Output\latest_run.png')